version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    working_directory: ~/AutomationFlamingo # directory where steps will run
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory

      # Which version of bundler?
      - run:
          name: Which bundler?
          command: bundle -v

      # Restore bundle cache
      - run:
          name: Bundle Install
          command: bundle install
      
      - run:
          name: Run Test
          command: bundle exec cucumber
