source "https://rubygems.org"

#git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# Specify your gem's dependencies in my_lib.gemspec
group :test do
  gem 'cucumber'
  gem 'rspec'
  gem 'capybara'
  gem 'selenium-webdriver'
end
